{% set version = "2.02.187" %}

package:
  name: lvm2-split
  version: {{ version }}

source:
  url: ftp://sourceware.org/pub/lvm2/LVM2.{{ version }}.tgz
  sha256: 0e0d521a863a5db2440f2e1e7627ba82b70273ae4ab0bbe130851db0d58e5af1

build:
  number: 3
  skip: True  # [not linux]
  run_exports:
    - {{ pin_subpackage('libdevmapper', max_pin='x.x') }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - autoconf >=2.69
    - autoconf-archive
    - automake
    - make
    - pkg-config
  host:
    - libaio

outputs:
  - name: libdevmapper

    files:
      include:
        - "lib/libdevmapper.so*"
        - "lib/pkgconfig/devmapper.pc"
        - "include/libdevmapper.h"
    requirements:
      build:
        - {{ compiler('c') }}
        - {{ stdlib('c') }}
        - autoconf >=2.69
        - autoconf-archive
        - automake
        - make
      host:
        - libaio
    build:
      run_exports:
        - {{ pin_subpackage('libdevmapper', max_pin='x.x') }}
    test:
      commands:
        - test -f "${PREFIX}/lib/libdevmapper.so"
        - test -f "${PREFIX}/lib/pkgconfig/devmapper.pc"
        - test -f "${PREFIX}/include/libdevmapper.h"

  - name: lvm2

    files:
      include:
        - "bin/**/*"
        - "lib/**/*"
        - "libexec/**/*"
        - "share/**/*"
        - "etc/**/*"
      exclude:
        - "lib/libdevmapper.so*"
        - "lib/pkgconfig/devmapper.pc"
        - "include/libdevmapper.h"


    requirements:
      build:
        - {{ compiler('c') }}
        - {{ stdlib('c') }}
        - autoconf >=2.69
        - autoconf-archive
        - automake
        - make
      host:
        - libaio
        - util-linux
      run:
        - {{ pin_subpackage('libdevmapper', exact=True) }}

    test:
      commands:
        - lvm version
        - pvcreate --help
        - vgcreate --help
        - lvcreate --help

    extra:
      feedstock-name: libdevmapper
about:
  home: https://sourceware.org/dm/
  dev_url: https://sourceware.org/git/lvm2.git
  doc_url: https://www.sourceware.org/dm/
  license: LGPL-2.1-only
  license_file:
    - COPYING.LIB
  summary: Userspace library for the Linux device-mapper component.

extra:
  recipe-maintainers:
    - mbargull
    - ngam
